version: 2
updates:
- package-ecosystem: "maven"
  directory: "/"
  schedule:
    interval: "daily"
  target-branch: "6.15.x"
  ignore:
  - dependency-name: "org.eclipse.jetty"
    versions:
      - ">= 10.0.0"