#!/bin/bash -e

basename=$(basename $0)
dirname=$(dirname $0)
dirname=$(cd "$dirname" && pwd)
cd "$dirname"

# show message and exit
function die() {
  echo "$1"
  exit 1
}

# show usage and exit
function usage() {
  echo "usage: $basename <command> [options]"
  exit 2
}

# run maven
function mvn() {
  ./mvnw $*
}

function command_rebuild() {
  mvn clean install $*
}

function command_demo() {
  exec demo/app/bin/shell.sh $*
}

command="$1"
if [ -z "$command" ]; then
  usage
fi
shift

case "$command" in
# install artifacts to local repository
install)
  mvn clean install $*
  ;;

# deploy to Sonatype snapshot-repository
deploy)
  mvn deploy -DskipTests -B -Dlicense.skip=true $*
  echo "Successfully deployed SNAPSHOT artifacts to Sonatype"
  ;;

# prepare release
release-prepare)
  mvn release:clean release:prepare
  ;;

# perform release
release-perform)
  mvn release:perform
  ;;

# clean release
release-clean)
  mvn release:clean
  ;;

# rollback release
release-rollback)
  mvn release:rollback
  ;;

*)
  # attempt to lookup command function
  fn="command_$command"
  if [ "$(type -t $fn)" = 'function' ]; then
    $fn $*
  else
    # complain about missing command function
    echo "Unknown command: $command"
    usage
  fi
  ;;
esac
