INSERT INTO vets VALUES (NEXT VALUE FOR BASE_ENTITY_ID_SEQ, 'James', 'Carter');
INSERT INTO vets VALUES (NEXT VALUE FOR BASE_ENTITY_ID_SEQ, 'Helen', 'Leary');
INSERT INTO vets VALUES (NEXT VALUE FOR BASE_ENTITY_ID_SEQ, 'Linda', 'Douglas');
INSERT INTO vets VALUES (NEXT VALUE FOR BASE_ENTITY_ID_SEQ, 'Rafael', 'Ortega');
INSERT INTO vets VALUES (NEXT VALUE FOR BASE_ENTITY_ID_SEQ, 'Henry', 'Stevens');
INSERT INTO vets VALUES (NEXT VALUE FOR BASE_ENTITY_ID_SEQ, 'Sharon', 'Jenkins');

INSERT INTO specialties VALUES (NEXT VALUE FOR BASE_ENTITY_ID_SEQ, 'radiology');
INSERT INTO specialties VALUES (NEXT VALUE FOR BASE_ENTITY_ID_SEQ, 'surgery');
INSERT INTO specialties VALUES (NEXT VALUE FOR BASE_ENTITY_ID_SEQ, 'dentistry');

INSERT INTO vet_specialties VALUES (2, CURRENT VALUE FOR BASE_ENTITY_ID_SEQ - 3 + 1);
INSERT INTO vet_specialties VALUES (3, CURRENT VALUE FOR BASE_ENTITY_ID_SEQ - 3 + 2);
INSERT INTO vet_specialties VALUES (3, CURRENT VALUE FOR BASE_ENTITY_ID_SEQ - 3 + 3);
INSERT INTO vet_specialties VALUES (4, CURRENT VALUE FOR BASE_ENTITY_ID_SEQ - 3 + 2);
INSERT INTO vet_specialties VALUES (5, CURRENT VALUE FOR BASE_ENTITY_ID_SEQ - 3 + 1);

INSERT INTO types VALUES (NEXT VALUE FOR BASE_ENTITY_ID_SEQ, 'cat');
INSERT INTO types VALUES (NEXT VALUE FOR BASE_ENTITY_ID_SEQ, 'dog');
INSERT INTO types VALUES (NEXT VALUE FOR BASE_ENTITY_ID_SEQ, 'lizard');
INSERT INTO types VALUES (NEXT VALUE FOR BASE_ENTITY_ID_SEQ, 'snake');
INSERT INTO types VALUES (NEXT VALUE FOR BASE_ENTITY_ID_SEQ, 'bird');
INSERT INTO types VALUES (NEXT VALUE FOR BASE_ENTITY_ID_SEQ, 'hamster');

INSERT INTO owners VALUES (NEXT VALUE FOR BASE_ENTITY_ID_SEQ, 'George', 'Franklin', '110 W. Liberty St.', 'Madison', '6085551023');
INSERT INTO owners VALUES (NEXT VALUE FOR BASE_ENTITY_ID_SEQ, 'Betty', 'Davis', '638 Cardinal Ave.', 'Sun Prairie', '6085551749');
INSERT INTO owners VALUES (NEXT VALUE FOR BASE_ENTITY_ID_SEQ, 'Eduardo', 'Rodriquez', '2693 Commerce St.', 'McFarland', '6085558763');
INSERT INTO owners VALUES (NEXT VALUE FOR BASE_ENTITY_ID_SEQ, 'Harold', 'Davis', '563 Friendly St.', 'Windsor', '6085553198');
INSERT INTO owners VALUES (NEXT VALUE FOR BASE_ENTITY_ID_SEQ, 'Peter', 'McTavish', '2387 S. Fair Way', 'Madison', '6085552765');
INSERT INTO owners VALUES (NEXT VALUE FOR BASE_ENTITY_ID_SEQ, 'Jean', 'Coleman', '105 N. Lake St.', 'Monona', '6085552654');
INSERT INTO owners VALUES (NEXT VALUE FOR BASE_ENTITY_ID_SEQ, 'Jeff', 'Black', '1450 Oak Blvd.', 'Monona', '6085555387');
INSERT INTO owners VALUES (NEXT VALUE FOR BASE_ENTITY_ID_SEQ, 'Maria', 'Escobito', '345 Maple St.', 'Madison', '6085557683');
INSERT INTO owners VALUES (NEXT VALUE FOR BASE_ENTITY_ID_SEQ, 'David', 'Schroeder', '2749 Blackhawk Trail', 'Madison', '6085559435');
INSERT INTO owners VALUES (NEXT VALUE FOR BASE_ENTITY_ID_SEQ, 'Carlos', 'Estaban', '2335 Independence La.', 'Waunakee', '6085555487');

INSERT INTO pets VALUES (NEXT VALUE FOR BASE_ENTITY_ID_SEQ, 'Leo', DATE '2010-09-07', CURRENT VALUE FOR BASE_ENTITY_ID_SEQ - 16 + 1, CURRENT VALUE FOR BASE_ENTITY_ID_SEQ - 10 + 1);
INSERT INTO pets VALUES (NEXT VALUE FOR BASE_ENTITY_ID_SEQ, 'Basil', DATE '2012-08-06', CURRENT VALUE FOR BASE_ENTITY_ID_SEQ - 17 + 5, CURRENT VALUE FOR BASE_ENTITY_ID_SEQ - 11 + 2);
INSERT INTO pets VALUES (NEXT VALUE FOR BASE_ENTITY_ID_SEQ, 'Rosy', DATE '2011-04-17', CURRENT VALUE FOR BASE_ENTITY_ID_SEQ - 18 + 2, CURRENT VALUE FOR BASE_ENTITY_ID_SEQ - 12 + 3);
INSERT INTO pets VALUES (NEXT VALUE FOR BASE_ENTITY_ID_SEQ, 'Jewel', DATE '2010-03-07', CURRENT VALUE FOR BASE_ENTITY_ID_SEQ - 19 + 2, CURRENT VALUE FOR BASE_ENTITY_ID_SEQ - 13 + 3);
INSERT INTO pets VALUES (NEXT VALUE FOR BASE_ENTITY_ID_SEQ, 'Iggy', DATE '2010-11-30', CURRENT VALUE FOR BASE_ENTITY_ID_SEQ - 20 + 3, CURRENT VALUE FOR BASE_ENTITY_ID_SEQ - 14 + 4);
INSERT INTO pets VALUES (NEXT VALUE FOR BASE_ENTITY_ID_SEQ, 'George', DATE '2010-01-20', CURRENT VALUE FOR BASE_ENTITY_ID_SEQ - 21 + 4, CURRENT VALUE FOR BASE_ENTITY_ID_SEQ - 15 + 5);
INSERT INTO pets VALUES (NEXT VALUE FOR BASE_ENTITY_ID_SEQ, 'Samantha', DATE '2012-09-04', CURRENT VALUE FOR BASE_ENTITY_ID_SEQ - 22 + 1, CURRENT VALUE FOR BASE_ENTITY_ID_SEQ - 16 + 6);
INSERT INTO pets VALUES (NEXT VALUE FOR BASE_ENTITY_ID_SEQ, 'Max', DATE '2012-09-04', CURRENT VALUE FOR BASE_ENTITY_ID_SEQ - 23 + 1, CURRENT VALUE FOR BASE_ENTITY_ID_SEQ - 17 + 6);
INSERT INTO pets VALUES (NEXT VALUE FOR BASE_ENTITY_ID_SEQ, 'Lucky', DATE '2011-08-06', CURRENT VALUE FOR BASE_ENTITY_ID_SEQ - 24 + 5, CURRENT VALUE FOR BASE_ENTITY_ID_SEQ - 18 + 7);
INSERT INTO pets VALUES (NEXT VALUE FOR BASE_ENTITY_ID_SEQ, 'Mulligan', DATE '2007-02-24', CURRENT VALUE FOR BASE_ENTITY_ID_SEQ - 25 + 2, CURRENT VALUE FOR BASE_ENTITY_ID_SEQ - 19 + 8);
INSERT INTO pets VALUES (NEXT VALUE FOR BASE_ENTITY_ID_SEQ, 'Freddy', DATE '2010-03-09', CURRENT VALUE FOR BASE_ENTITY_ID_SEQ - 26 + 5, CURRENT VALUE FOR BASE_ENTITY_ID_SEQ - 20 + 9);
INSERT INTO pets VALUES (NEXT VALUE FOR BASE_ENTITY_ID_SEQ, 'Lucky', DATE '2010-06-24', CURRENT VALUE FOR BASE_ENTITY_ID_SEQ - 27 + 2, CURRENT VALUE FOR BASE_ENTITY_ID_SEQ - 21 + 9);
INSERT INTO pets VALUES (NEXT VALUE FOR BASE_ENTITY_ID_SEQ, 'Sly', DATE '2012-06-08', CURRENT VALUE FOR BASE_ENTITY_ID_SEQ - 28 + 1, CURRENT VALUE FOR BASE_ENTITY_ID_SEQ - 22 + 9);

INSERT INTO visits VALUES (NEXT VALUE FOR BASE_ENTITY_ID_SEQ, CURRENT VALUE FOR BASE_ENTITY_ID_SEQ - 13 + 7, DATE '2013-01-01', 'rabies shot');
INSERT INTO visits VALUES (NEXT VALUE FOR BASE_ENTITY_ID_SEQ, CURRENT VALUE FOR BASE_ENTITY_ID_SEQ - 14 + 8, DATE '2013-01-02', 'rabies shot');
INSERT INTO visits VALUES (NEXT VALUE FOR BASE_ENTITY_ID_SEQ, CURRENT VALUE FOR BASE_ENTITY_ID_SEQ - 15 + 8, DATE '2013-01-03', 'neutered');
INSERT INTO visits VALUES (NEXT VALUE FOR BASE_ENTITY_ID_SEQ, CURRENT VALUE FOR BASE_ENTITY_ID_SEQ - 16 + 7, DATE '2013-01-04', 'spayed');