/*
 * Copyright (c) 2008-present The Aspectran Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.aspectran.core.scheduler.activity;

import com.aspectran.utils.logging.LoggingGroupHelper;
import org.quartz.JobExecutionContext;
import org.quartz.JobExecutionException;
import org.quartz.JobListener;

/**
 * A Quartz {@link JobListener} implementation that integrates with Aspectran's logging
 * and job reporting mechanisms.
 * <p>This listener is responsible for setting the appropriate logging group for scheduled
 * jobs and delegating job execution events to {@link ActivityJobReporter} for detailed logging.</p>
 *
 * @since 3.0.0
 */
public class ActivityJobListener implements JobListener {

    private static final String LISTENER_NAME = "activityJobListener";

    private final String loggingGroup;

    /**
     * Constructs an ActivityJobListener with a specific logging group.
     * @param loggingGroup the name of the logging group to set for jobs handled by this listener
     */
    public ActivityJobListener(String loggingGroup) {
        this.loggingGroup = loggingGroup;
    }

    /**
     * Returns the name of this JobListener.
     * @return the listener name
     */
    @Override
    public String getName() {
        return LISTENER_NAME;
    }

    /**
     * Called by the Quartz scheduler when a Job is about to be executed.
     * Sets the logging group and reports the event to {@link ActivityJobReporter}.
     * @param context the context for the job execution
     */
    @Override
    public void jobToBeExecuted(JobExecutionContext context) {
        setLoggingGroup();
        ActivityJobReporter.jobToBeExecuted(context, false);
    }

    /**
     * Called by the Quartz scheduler when a Job execution is vetoed (prevented).
     * Sets the logging group and reports the event to {@link ActivityJobReporter}.
     * @param context the context for the job execution
     */
    @Override
    public void jobExecutionVetoed(JobExecutionContext context) {
        setLoggingGroup();
        ActivityJobReporter.jobToBeExecuted(context, true);
    }

    /**
     * Called by the Quartz scheduler after a Job has been executed.
     * Sets the logging group and reports the event to {@link ActivityJobReporter}.
     * @param context the context for the job execution
     * @param jobException the exception thrown by the job, or {@code null} if no exception
     */
    @Override
    public void jobWasExecuted(JobExecutionContext context, JobExecutionException jobException) {
        setLoggingGroup();
        ActivityJobReporter.jobWasExecuted(context, jobException);
    }

    /**
     * Sets the current logging group using {@link LoggingGroupHelper}.
     * This ensures that logs generated by the scheduled job are categorized correctly.
     */
    private void setLoggingGroup() {
        if (loggingGroup != null) {
            LoggingGroupHelper.set(loggingGroup);
        }
    }

}
