name: Coveralls
on: [push, pull_request]
jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[maven-release-plugin]')"
    name: Coveralls
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: temurin
      - name: Report Coverage to Coveralls for Pull Requests
        if: github.event_name == 'pull_request'
        run: ./mvnw -B -V test jacoco:report coveralls:report -q -D"license.skip=true" -D"repoToken=$GITHUB_TOKEN" -D"serviceName=github" -D"pullRequest=$PR_NUMBER"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.number }}
      - name: Report Coverage to Coveralls for General Push
        if: github.event_name == 'push'
        run: ./mvnw -B -V test jacoco:report coveralls:report -q -D"license.skip=true" -D"repoToken=$GITHUB_TOKEN" -D"serviceName=github"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
